service: fileUploader
frameworkVersion: '3'
# useDotenv: true
plugins:
  # - serverless-plugin-typescript
  # - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    # API のパスは `https://<domainName>/<basePath>/xxxx` となる
    domainName: 'kenmiki.com'
    basePath: ''
    certificateName: 'kenmiki.com'
    certificateArn: 'arn:aws:acm:ap-northeast-1:200966924140:certificate/259867ef-1d78-458c-84cd-dce8450a028b'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: 'tls_1_2'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  profile: serverless

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
