# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: ci
on:
  pull_request:
    branches: ["**"]
# permission can be added at job level or workflow level
permissions:
  contents: read # This is required for actions/checkout
jobs:
  BuildFrontTest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: package install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: cd front && npm ci
      - name: build
        run: cd front && npm run build
