# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: front deploy on AWS
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
